# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb5d3439b9374e4b6ae90c8ac460aecd7828e35e2eb3c28a12c4b9d01a0dea2367538f22787dc33cb25a726caa0b6cab11ed049eaf0c542c2f7f199355e48f7f

test:
  secret_key_base: da6d049f661e60dd77cf0d931d75f5375d88dfe82f62539f498d64f1ceaa4c492610f57a60ea8faab2d12c3b756d891f973db735dfb63fedb3600b5f19020564

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
